slug = "eccentric-dual"
title = "Eccentric Dual"
author = "Stephen"
value = 50
description = """I built a pseudo-original elliptic-curve-based pseudorandom number generator, which I usually use for my phone passcodes. I've only had to use [these](sample_output.txt) first 2 rows. The flag for this challenge is the 21st row of output, using the same seed. Here's the [code](NIST_ESQUE_DUAL_EC_RBG.py) if you wanna take a look, but I hid the seed, so you shouldn't ever be able to figure it out anyways."""
tags = ["modern"]
files = ["sample_output.txt", "NIST_ESQUE_DUAL_EC_RBG.py"]
flag = "flag{868523750842848084007710195422446292}"
enabled = true
