slug = "eccentric-dual"
title = "Eccentric Dual"
author = "Stephen"
value = 50
description = """I built my very own (version of a well-established) elliptic-curve-based pseudorandom number generator, which I usually use for my phone passcodes. I've only had to output 2 rows worth of pseudorandom numbers, which I have [here](sample_output.txt). I went ahead and used the same seed to generate a bunch more rows, which I am not gonna show you, and I just used the 21st row as the flag for the challenge. Here's the [code](NIST_ESQUE_DUAL_EC_RBG.py) if you wanna take a look, but I hid the seed, so you shouldn't ever be able to figure it out anyways."""
tags = ["modern"]
files = ["sample_output.txt", "NIST_ESQUE_DUAL_EC_RBG.py"]
flag = "flag{868523750842848084007710195422446292}"
enabled = true
