slug = "cool-slug-here"
title = "This is the name of my cool title!"
author = "Cool kid"
value = 100
description = """Very cool feedback form [here](https://forms.gle/DpMohPXKsTp2bwoSA)."""
tags = ["feedback"]
files = []
flag = "flag{this_flag_is_cool}"
enabled = false

